version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: active-fedora
    versions:
    - "< 10, >= 9.a"
  - dependency-name: active-fedora
    versions:
    - "< 11, >= 10.a"
  - dependency-name: nom-xml
    versions:
    - "< 2, >= 1.a"
  - dependency-name: rails
    versions:
    - "< 6, >= 5.a"
  - dependency-name: rubydora
    versions:
    - "< 2, > 1.8.1"
  - dependency-name: sqlite3
    versions:
    - ">= 1.4.a, < 1.5"
  - dependency-name: nokogiri
    versions:
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.12.1
